import type { NextPage } from "next";
import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import FloatingButtons from "../components/FloatingButtons";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import gsap from "gsap/dist/gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import CasquetsLogo from "../components/Casquets/Logo";

gsap.registerPlugin(ScrollTrigger);

// Images
import HeroImage from "../public/images/hero-compressed.jpg";
import theodolite from "../public/images/construction-1212730.jpg";
import Button from "../components/utilities/button";
import Reviews from "../components/Review";
import ServiceSection from "../components/Sections/ServiceSection";
import StatsBlock from "../components/StatsBlock";
import Contact from "../components/Contact";

const Home: NextPage = () => {
  useEffect(() => {
    gsap.from(".pContainer", {
      yPercent: 10,
      ease: "none",
      scrollTrigger: {
        trigger: ".pSection",
        // start: "top bottom", // the default values
        // end: "bottom top",
        scrub: true,
      },
    });
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FloatingButtons />
      <div className="bg-white/40 w-full fixed z-20 dark:bg-[#1B2834]/40 backdrop-blur-lg">
        <div className="container px-10 xl:px-20 mx-auto">
          <Navbar />
        </div>
      </div>
      <div className="container px-10 xl:px-20 mx-auto pt-44">
        <Hero />
      </div>
      <main className="pSection">
        <div className="w-full diagonal-clip text-[0] overflow-hidden">
          <div className="pContainer ">
            <div className="scale-125">
              <Image src={HeroImage} objectFit="fill" alt="Image of surveyor" />
            </div>
          </div>
        </div>
        {/*  */}
        <ServiceSection />
        <div className="bg-[#F8FEFF] dark:bg-[#00456B]">
          <section className="pt-10 pb-20 container max-w-screen-xl flex flex-wrap mt-10 px-10 md:px-20 mx-auto">
            <div className="flex flex-col-reverse md:flex-row w-full gap-20">
              <div className="md:w-1/2 lg:w-2/3">
                <h2 className="w-full font-bold text-4xl py-10">O Nas</h2>
                <p className="py-10">
                  I&apos;m baby keffiyeh woke church-key, glossier jianbing
                  schlitz fingerstache PBR&B ugh humblebrag hammock dreamcatcher
                  fam. Normcore trust fund four dollar toast leggings quinoa af
                  flannel prism viral live-edge skateboard before they sold out
                  tattooed. Fixie skateboard craft beer, next level distillery
                  +1 kickstarter hexagon vaporware. Fingerstache lyft retro
                  bespoke iceland, yr gastropub chartreuse polaroid normcore
                  vice cold-pressed taxidermy coloring book. Stumptown tofu
                  humblebrag shaman activated charcoal. 3 wolf moon tacos
                  bitters roof party viral PBR&B sriracha disrupt cornhole echo
                  park biodiesel.
                </p>
                <Button size="large" url="http://google.com">
                  Wycena bez zobowiązań
                </Button>
              </div>
              <div className="md:w-1/2 lg:w-1/3">
                <div className="mt-10 mx-auto relative rounded-t-full rounded-b-full overflow-hidden text-[0]">
                  <Image src={theodolite} alt="Theodolite" objectFit="fill" />
                </div>
              </div>
            </div>
            <aside className="py-10 w-full md:flex">
              <StatsBlock statistic={"36"} description="Doświadczenia" />
              <StatsBlock
                statistic={"1,9k"}
                description="Projekty Zakończone"
              />
              <StatsBlock
                statistic={"236+"}
                description="Zadowolonych Klientów"
              />
            </aside>
          </section>
        </div>
        <section className="container py-32 px-10 md:px-20  max-w-screen-xl mx-auto">
          <h2 className="w-full font-bold text-4xl pb-20">Referencje</h2>
          <Reviews />
        </section>
      </main>
      <footer className="w-full">
        <Contact />
        <div className="bg-[#2B3048] text-white w-full py-4 px-10 flex flex-wrap gap-2">
          <div className="h-5">
            <CasquetsLogo />
          </div>
          <div className="pt-2 text-xs text-right">
            Copyright © 2022 | Casquets Web Designs | All Rights Reserved
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Home;
